import { apiClient, toFormData, type QueryParams } from "./client";

export const appApi = {
  getThemes: () => apiClient.get("/meta/themes"),
  getLeaderboardConfig: () => apiClient.get("/leaderboard/config"),
  getLeaderboardList: (params?: QueryParams) => apiClient.get("/leaderboard/list", { params }),
  getCurrencyMeta: () => apiClient.get("/meta/currency"),
  getWalletLedger: (params?: QueryParams) => apiClient.get("/wallet/ledger", { params: { limit: 20, ...params } }),
  getRechargeStatus: (orderId: string) => apiClient.get("/recharge/status", { params: { orderId } }),
  getMaterialOverridesMeta: () => apiClient.get("/meta/material-overrides"),
  getMaterialsMeta: () => apiClient.get("/meta/materials"),
  getMarketTagsMeta: () => apiClient.get("/meta/market-tags"),
  getWallet: () => apiClient.get("/wallet"),
  getOrdersHomeList: (params?: QueryParams) => apiClient.get("/orders/list", { params: { limit: 30, ...params } }),
  getOrdersPageList: (params?: QueryParams) => apiClient.get("/orders/list", { params: { limit: 50, ...params } }),
  getMyListings: (params?: QueryParams) => apiClient.get("/market/listings", { params: { mine: true, limit: 80, ...params } }),
  getMarketListings: (params?: QueryParams) => apiClient.get("/market/listings", { params }),
  getUnreadNotificationsCount: () => apiClient.get("/notifications/unread-count"),
  getProducts: (params?: QueryParams) => apiClient.get("/products", { params }),
  getOrdersPolicy: () => apiClient.get("/orders/policy"),
  getNotificationsList: (params?: QueryParams) => apiClient.get("/notifications/list", { params: { limit: 50, ...params } }),
  markNotificationsRead: (payload: Record<string, unknown>) => apiClient.post("/notifications/mark-read", payload),
  refundOrder: (payload: Record<string, unknown>) => apiClient.post("/orders/refund", payload),
  createOrder: (payload: Record<string, unknown>) => apiClient.post("/orders", payload),
  createMarketListing: (payload: Record<string, unknown>) => apiClient.post("/market/listings/create", payload),
  buyMarketListing: (payload: Record<string, unknown>) => apiClient.post("/market/buy", payload),
  sellToBuyListing: (payload: Record<string, unknown>) => apiClient.post("/market/sell-to-buy", payload),
  bidMarketListing: (payload: Record<string, unknown>) => apiClient.post("/market/bid", payload),
  unlistMarketListing: (payload: Record<string, unknown>) => apiClient.post("/market/unlist", payload),
  refreshMarketSupply: (payload?: Record<string, unknown>) => apiClient.post("/market/supply/refresh", payload ?? {}),
  pauseMarketListing: (payload: Record<string, unknown>) => apiClient.post("/market/pause", payload),
  resumeMarketListing: (payload: Record<string, unknown>) => apiClient.post("/market/resume", payload),
  updateMarketPrice: (payload: Record<string, unknown>) => apiClient.post("/market/price", payload),
  updateMarketRemark: (payload: Record<string, unknown>) => apiClient.post("/market/remark", payload),
  updateMarketSettings: (payload: Record<string, unknown>) => apiClient.post("/market/settings", payload),
  login: (payload: Record<string, unknown>) => apiClient.post("/auth/login", payload),
  logout: (payload?: Record<string, unknown>) => apiClient.post("/auth/logout", payload ?? {}),
  createRechargeOrder: (payload: Record<string, unknown>) => apiClient.post("/recharge/create", payload),
  useRedeemCode: (payload: Record<string, unknown>) => apiClient.post("/redeem/use", payload),
  walletExchange: (payload: Record<string, unknown>) => apiClient.post("/wallet/exchange", payload),
  uploadMarketIcon: (query: QueryParams, payload: Record<string, unknown>) =>
    apiClient.post("/market/icon/upload", toFormData(payload), {
      params: query,
      headers: { "Content-Type": "multipart/form-data" },
    }),
};
