import { appApi } from "./app";

export const shopApi = {
  getThemes: appApi.getThemes,
  getLeaderboardConfig: appApi.getLeaderboardConfig,
  getLeaderboardList: appApi.getLeaderboardList,
  getCurrencyMeta: appApi.getCurrencyMeta,
  getMaterialOverridesMeta: appApi.getMaterialOverridesMeta,
  getMaterialsMeta: appApi.getMaterialsMeta,
  getMarketTagsMeta: appApi.getMarketTagsMeta,
  getProducts: appApi.getProducts,
  getOrdersPolicy: appApi.getOrdersPolicy,
  getOrdersHomeList: appApi.getOrdersHomeList,
  getOrdersPageList: appApi.getOrdersPageList,
  createOrder: appApi.createOrder,
  refundOrder: appApi.refundOrder,
  getMyListings: appApi.getMyListings,
  getMarketListings: appApi.getMarketListings,
  createMarketListing: appApi.createMarketListing,
  buyMarketListing: appApi.buyMarketListing,
  sellToBuyListing: appApi.sellToBuyListing,
  bidMarketListing: appApi.bidMarketListing,
  unlistMarketListing: appApi.unlistMarketListing,
  refreshMarketSupply: appApi.refreshMarketSupply,
  pauseMarketListing: appApi.pauseMarketListing,
  resumeMarketListing: appApi.resumeMarketListing,
  updateMarketPrice: appApi.updateMarketPrice,
  updateMarketRemark: appApi.updateMarketRemark,
  updateMarketSettings: appApi.updateMarketSettings,
  uploadMarketIcon: appApi.uploadMarketIcon,
};
